In [2]:
import numpy as np

n=int(input("Enter the size of the problem "))
print("Think of an integer from 1 to",n**n)
a=np.zeros((n**(n-1),n))
for i in range(n**(n-1)):
	a[i,:]=np.arange(i*n+1,(i+1)*n+1)
num=1
for i in range(n):
    print(a)
    l=int(input("Enter the column number "))
    num+=(l-1)*(n**i)
    b=np.zeros((n**(n-1),n))
    for j in range(n**(n-1)):
        for k in range(n):
            b[j,k]=a[(j*n+k)%(n**(n-1)),(j*n+k)//(n**(n-1))]
    a=b
print("The number you thought is",num)

Enter the size of the problem  3


Think of an integer from 1 to 27
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]
 [22. 23. 24.]
 [25. 26. 27.]]


Enter the column number  2


[[ 1.  4.  7.]
 [10. 13. 16.]
 [19. 22. 25.]
 [ 2.  5.  8.]
 [11. 14. 17.]
 [20. 23. 26.]
 [ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


Enter the column number  3


[[ 1. 10. 19.]
 [ 2. 11. 20.]
 [ 3. 12. 21.]
 [ 4. 13. 22.]
 [ 5. 14. 23.]
 [ 6. 15. 24.]
 [ 7. 16. 25.]
 [ 8. 17. 26.]
 [ 9. 18. 27.]]


Enter the column number  2


The number you thought is 17


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,3,4]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 3 4]]
