In [4]:
import numpy as np
n = int(input("Enter odd number "))
sum = int(input("Enter the sum "))
f = sum/n - (n*n - 1)/2
k1 = n//2
k2 = n - 1
a = np.zeros([n,n])

for i in range(n):
          a[k1,k2] = f
          for j in range(n-1):
              f = f + 1
              k1 = (k1-1)%n
              k2 = (k2+1)%n
              a[k1,k2] = f
          f = f + 1
          k2 = (k2 - 1)%n
print(a)
        

Enter odd number  5
Enter the sum  285


[[53. 47. 66. 60. 59.]
 [46. 65. 64. 58. 52.]
 [69. 63. 57. 51. 45.]
 [62. 56. 50. 49. 68.]
 [55. 54. 48. 67. 61.]]


In [2]:
import numpy as np
l = np.zeros([5,5])
print(l)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
