In [1]:
# Rewrite the code game reshape.txt (uploaded in hello iitk portal) by replacing the numpy.reshape commands 
# into a user-defined subroutine. In other words, you need to write a user-defined function that implements
# numpy.reshape, and test it on the given code.

import numpy as np

n=int(input("Enter the size of the problem "))
print("Think of an integer from 1 to",n**n)
a=np.reshape(np.arange(1,n**n+1),(n**(n-1),n))
num=1
for i in range(n):
    print(a)
    l=int(input("Enter the column number "))
    num+=(l-1)*(n**i)
    b=np.reshape(a.T,(n**(n-1),n))
    a=b
print("The number you thought is",num)

Enter the size of the problem  3


Think of an integer from 1 to 27
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


Enter the column number  1


[[ 1  4  7]
 [10 13 16]
 [19 22 25]
 [ 2  5  8]
 [11 14 17]
 [20 23 26]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


Enter the column number  1


[[ 1 10 19]
 [ 2 11 20]
 [ 3 12 21]
 [ 4 13 22]
 [ 5 14 23]
 [ 6 15 24]
 [ 7 16 25]
 [ 8 17 26]
 [ 9 18 27]]


Enter the column number  3


The number you thought is 19


In [10]:
import numpy as np
def reshape1(ar,a,b):
    ar=ar.flatten()
    z=np.zeros((a,b))
    c=0
    for i in range(a):
        for j in range(b):
            z[i,j] = ar[c]
            c += 1
    return z
result = reshape1(np.arange(1, 19), 6, 3)
print(result)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [3]:
import numpy as np

def reshape1(ar, a, b):
    ar = ar.flatten()
    z = np.zeros((a, b))  # Corrected the shape argument for np.zeros
    c = 0
    for i in range(a):
        for j in range(b):
            z[i, j] = ar[c]
            c += 1
    return z

result = reshape1(np.arange(1, 19), 6, 3)
print(result)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
