In [8]:
a,b=input("Enter 2 numbers to calculate GCD and LCM: ").split()
a = int(a)
b = int(b)
num1 = int(a)
num2 = int(b)
l=1
while l != 0 :
    l=a%b
    a=b
    b=l
print("Greatest Common Divisor:",a)

s=num1*num2/a
print("Lowest Common Multiple: " + str(s))

Enter 2 numbers to calculate GCD and LCM:  76 54


Greatest Common Divisor: 2
Lowest Common Multiple: 2052.0


In [1]:
import numpy as np
x = list(map(int,input("Enter the elements of a matrix row wise-linearly, separated with a space: ").split()))
m,n = list(map(int,input("Enter the dimensions of the matrix, separated with a space: ").split()))
z = np.reshape(x,(m,n))
print(z)

Enter the elements of a matrix row wise-linearly, separated with a space:  1 2 3 2 4 5 3 8 10
Enter the dimensions of the matrix, separated with a space:  3 3


[[ 1  2  3]
 [ 2  4  5]
 [ 3  8 10]]
